[package]
name = "slack-rs"
version = "0.1.0"
authors = ["Yuya Minami <yuya373@me.com>"]

[dependencies]
futures = "0.1"
tokio = "0.1"
reqwest = "0.9.0"
serde_derive = "1.0"
serde = "1.0"
toml = "0.4.2"
dirs = "1.0.3"

[dependencies.ws]
version = "0.7.8"
features = ["ssl"]
