[package]
name = "slack-rs"
version = "0.1.0"
authors = ["Yuya Minami <yuya373@me.com>"]

[dependencies]
reqwest = "0.9.0"
serde_derive = "1.0"
serde = "1.0"

[dependencies.ws]
version = "0.7.8"
features = ["ssl"]
